name: Borsa Kahini

on:
  schedule:
    # Pazartesi sabah 09:30 (TSİ) için UTC 06:30
    - cron: '30 6 * * 1'
  workflow_dispatch: # Elle tetiklemek için buton

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v2

      - name: Python Kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install pandas numpy yfinance requests

      - name: Analizi Başlat
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
