Name: Borsa Kahini

on:
  schedule:
    # Pazartesi sabah 09:30 (TSİ) için UTC 06:30
    - cron: '30 6 * * 1'
  workflow_dispatch: # Elle tetiklemek için buton

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Bağımlılıkları önbelleğe alır, hız kazandırır

      - name: Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests yfinance==0.2.40

      - name: Analizi Başlat
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
