name: Borsa Kahini

on:
  schedule:
    - cron: '30 6 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      # Python 3.9 kullanmaya devam etse bile çalışacak önlem
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Kütüphaneleri Yükle (Eski ve Kararlı Sürüm)
        run: |
          python -m pip install --upgrade pip
          # Önbelleği kapat (--no-cache-dir) ve eski sağlam sürümü kur
          pip install pandas numpy requests yfinance==0.2.18 --no-cache-dir

      - name: Analizi Başlat
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
